integrate-tcl.diff: integrats tcl and fills in the target vector

diff --git a/gdb/configure b/gdb/configure
--- a/gdb/configure
+++ b/gdb/configure
@@ -863,6 +863,7 @@ Optional Features:
   --enable-targets        alternative target configurations
   --enable-64-bit-bfd     64-bit support (on hosts with narrower word sizes)
   --disable-gdbcli        disable command-line interface (CLI)
+  --disable-gdbtgif        disable command-line interface (TCL)
   --disable-gdbmi         disable machine-interface (MI)
   --enable-tui            enable full-screen terminal user interface (TUI)
   --enable-gdbtk          enable gdbtk graphical user interface (GUI)
@@ -3120,6 +3121,7 @@ else
   gdb_native=no
 fi
 
+
 . $srcdir/configure.host
 
 # Accumulate some settings from configure.tgt over all enabled targets
@@ -3836,6 +3838,94 @@ fi
 
 
 
+
+if test $ac_cv_target_alias = qdsp6; then
+
+cat >>confdefs.h <<\_ACEOF
+#define TCL_PROMPT "% "
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define DEFAULT_PROMPT "(qdsp6-gdb) "
+_ACEOF
+
+
+echo "$as_me:$LINENO: checking for dlopen in -ldl" >&5
+echo $ECHO_N "checking for dlopen in -ldl... $ECHO_C" >&6
+if test "${ac_cv_lib_dl_dlopen+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ldl  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char dlopen ();
+int
+main ()
+{
+dlopen ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_dl_dlopen=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_dl_dlopen=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_dl_dlopen" >&5
+echo "${ECHO_T}$ac_cv_lib_dl_dlopen" >&6
+if test $ac_cv_lib_dl_dlopen = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBDL 1
+_ACEOF
+
+  LIBS="-ldl $LIBS"
+
+fi
+
+fi
+
 # For other settings, only the main target counts.
 gdb_sim=
 gdb_osabi=
@@ -3905,6 +3995,36 @@ if test x"$enable_gdbcli" = xyes; then
     CONFIG_DEPS="$CONFIG_DEPS \$(SUBDIR_CLI_DEPS)"
     CONFIG_SRCS="$CONFIG_SRCS \$(SUBDIR_CLI_SRCS)"
     ENABLE_CFLAGS="$ENABLE_CFLAGS \$(SUBDIR_CLI_CFLAGS)"
+  fi
+fi
+
+# The TCL cannot be disabled yet, but may be in the future.
+
+# Enable TCL.
+# Check whether --enable-gdbtgif or --disable-gdbtgif was given.
+if test "${enable_gdbtgif+set}" = set; then
+  enableval="$enable_gdbtgif"
+  case $enableval in
+    yes)
+      ;;
+    no)
+      { { echo "$as_me:$LINENO: error: the command-line interface cannot be disabled yet" >&5
+echo "$as_me: error: the command-line interface cannot be disabled yet" >&2;}
+   { (exit 1); exit 1; }; } ;;
+    *)
+      { { echo "$as_me:$LINENO: error: bad value $enableval for --enable-gdbtgif" >&5
+echo "$as_me: error: bad value $enableval for --enable-gdbtgif" >&2;}
+   { (exit 1); exit 1; }; } ;;
+  esac
+else
+  enable_gdbtgif=yes
+fi;
+if test x"$enable_gdbtgif" = xyes; then
+  if test -d $srcdir/tgif; then
+    CONFIG_OBS="$CONFIG_OBS \$(SUBDIR_TGIF_OBS)"
+    CONFIG_DEPS="$CONFIG_DEPS \$(SUBDIR_TGIF_DEPS)"
+    CONFIG_SRCS="$CONFIG_SRCS \$(SUBDIR_TGIF_SRCS)"
+    ENABLE_CFLAGS="$ENABLE_CFLAGS \$(SUBDIR_TGIF_CFLAGS)"
   fi
 fi
 
